package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * Dangkymonhoc generated by hbm2java
 */
public class Dangkymonhoc  implements java.io.Serializable {


     private DangkymonhocId id;

    public Dangkymonhoc() {
    }

    public Dangkymonhoc(DangkymonhocId id) {
       this.id = id;
    }
   
    public DangkymonhocId getId() {
        return this.id;
    }
    
    public void setId(DangkymonhocId id) {
        this.id = id;
    }




}


