package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * DangkymonhocId generated by hbm2java
 */
public class DangkymonhocId  implements java.io.Serializable {


     private String maLop;
     private String maMh;
     private String mssv;
     private int namHoc;

    public DangkymonhocId() {
    }

    public DangkymonhocId(String maLop, String maMh, String mssv, int namHoc) {
       this.maLop = maLop;
       this.maMh = maMh;
       this.mssv = mssv;
       this.namHoc = namHoc;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public int getNamHoc() {
        return this.namHoc;
    }
    
    public void setNamHoc(int namHoc) {
        this.namHoc = namHoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DangkymonhocId) ) return false;
		 DangkymonhocId castOther = ( DangkymonhocId ) other; 
         
		 return ( (this.getMaLop()==castOther.getMaLop()) || ( this.getMaLop()!=null && castOther.getMaLop()!=null && this.getMaLop().equals(castOther.getMaLop()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) )
 && ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) )
 && (this.getNamHoc()==castOther.getNamHoc());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaLop() == null ? 0 : this.getMaLop().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         result = 37 * result + this.getNamHoc();
         return result;
   }   


}


