package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private DiemId id;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTk;

    public Diem() {
    }

	
    public Diem(DiemId id) {
        this.id = id;
    }
    public Diem(DiemId id, Float diemGk, Float diemCk, Float diemKhac, Float diemTk) {
       this.id = id;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTk = diemTk;
    }
   
    public DiemId getId() {
        return this.id;
    }
    
    public void setId(DiemId id) {
        this.id = id;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTk() {
        return this.diemTk;
    }
    
    public void setDiemTk(Float diemTk) {
        this.diemTk = diemTk;
    }




}


