package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * Khac generated by hbm2java
 */
public class Khac  implements java.io.Serializable {


     private String loaiDuLieu;
     private String cot1;
     private String cot2;

    public Khac() {
    }

    public Khac(String loaiDuLieu, String cot1, String cot2) {
       this.loaiDuLieu = loaiDuLieu;
       this.cot1 = cot1;
       this.cot2 = cot2;
    }
   
    public String getLoaiDuLieu() {
        return this.loaiDuLieu;
    }
    
    public void setLoaiDuLieu(String loaiDuLieu) {
        this.loaiDuLieu = loaiDuLieu;
    }
    public String getCot1() {
        return this.cot1;
    }
    
    public void setCot1(String cot1) {
        this.cot1 = cot1;
    }
    public String getCot2() {
        return this.cot2;
    }
    
    public void setCot2(String cot2) {
        this.cot2 = cot2;
    }




}


