package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * PhuckhaoId generated by hbm2java
 */
public class PhuckhaoId  implements java.io.Serializable {


     private String mssv;
     private String maLop;
     private String maMh;
     private String cotDiem;

    public PhuckhaoId() {
    }

    public PhuckhaoId(String mssv, String maLop, String maMh, String cotDiem) {
       this.mssv = mssv;
       this.maLop = maLop;
       this.maMh = maMh;
       this.cotDiem = cotDiem;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public String getCotDiem() {
        return this.cotDiem;
    }
    
    public void setCotDiem(String cotDiem) {
        this.cotDiem = cotDiem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhuckhaoId) ) return false;
		 PhuckhaoId castOther = ( PhuckhaoId ) other; 
         
		 return ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) )
 && ( (this.getMaLop()==castOther.getMaLop()) || ( this.getMaLop()!=null && castOther.getMaLop()!=null && this.getMaLop().equals(castOther.getMaLop()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) )
 && ( (this.getCotDiem()==castOther.getCotDiem()) || ( this.getCotDiem()!=null && castOther.getCotDiem()!=null && this.getCotDiem().equals(castOther.getCotDiem()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         result = 37 * result + ( getMaLop() == null ? 0 : this.getMaLop().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         result = 37 * result + ( getCotDiem() == null ? 0 : this.getCotDiem().hashCode() );
         return result;
   }   


}


