package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * Phuckhao generated by hbm2java
 */
public class Phuckhao  implements java.io.Serializable {


     private PhuckhaoId id;
     private String hoTen;
     private String diemMongMuon;
     private String lyDo;
     private String tinhTrang;

    public Phuckhao() {
    }

	
    public Phuckhao(PhuckhaoId id, String hoTen) {
        this.id = id;
        this.hoTen = hoTen;
    }
    public Phuckhao(PhuckhaoId id, String hoTen, String diemMongMuon, String lyDo, String tinhTrang) {
       this.id = id;
       this.hoTen = hoTen;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
       this.tinhTrang = tinhTrang;
    }
   
    public PhuckhaoId getId() {
        return this.id;
    }
    
    public void setId(PhuckhaoId id) {
        this.id = id;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(String diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


