package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * Thoikhoabieu generated by hbm2java
 */
public class Thoikhoabieu  implements java.io.Serializable {


     private ThoikhoabieuId id;
     private String tenMh;
     private String phong;

    public Thoikhoabieu() {
    }

    public Thoikhoabieu(ThoikhoabieuId id, String tenMh, String phong) {
       this.id = id;
       this.tenMh = tenMh;
       this.phong = phong;
    }
   
    public ThoikhoabieuId getId() {
        return this.id;
    }
    
    public void setId(ThoikhoabieuId id) {
        this.id = id;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public String getPhong() {
        return this.phong;
    }
    
    public void setPhong(String phong) {
        this.phong = phong;
    }




}


