package POJO;
// Generated Jun 18, 2020 8:10:59 PM by Hibernate Tools 4.3.1



/**
 * ThoikhoabieuId generated by hbm2java
 */
public class ThoikhoabieuId  implements java.io.Serializable {


     private String maLop;
     private String maMh;

    public ThoikhoabieuId() {
    }

    public ThoikhoabieuId(String maLop, String maMh) {
       this.maLop = maLop;
       this.maMh = maMh;
    }
   
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ThoikhoabieuId) ) return false;
		 ThoikhoabieuId castOther = ( ThoikhoabieuId ) other; 
         
		 return ( (this.getMaLop()==castOther.getMaLop()) || ( this.getMaLop()!=null && castOther.getMaLop()!=null && this.getMaLop().equals(castOther.getMaLop()) ) )
 && ( (this.getMaMh()==castOther.getMaMh()) || ( this.getMaMh()!=null && castOther.getMaMh()!=null && this.getMaMh().equals(castOther.getMaMh()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaLop() == null ? 0 : this.getMaLop().hashCode() );
         result = 37 * result + ( getMaMh() == null ? 0 : this.getMaMh().hashCode() );
         return result;
   }   


}


